version: "3.7"

services:
  ActiveMQ:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
      AMQ_EXTRA_ARGS: --relax-jolokia
      

  Postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      # - "5432:5432"
      # {{port_postgres}}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      - PORT_POSTGRES=${port_postgres}

  SwaggerUI:
    image: swaggerapi/swagger-ui:latest
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres-data:
