version: "3.7"

services:
  ActiveMQ:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    ports:
      - "${PORT_ACTIVEMQ}:61616"
      - "${PORT_MON_ACTIVEMQ}:8161"
      # default:
      # 61616:61616
      # 8161:8161
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin
      AMQ_EXTRA_ARGS: --relax-jolokia

  Postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${PORT_POSTGR}:5432"
      # - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      
  SwaggerUI:
    image: swaggerapi/swagger-ui:latest
    restart: always
    ports:
      - "${PORT_SWAG}:8080"
      # - '8080:8080'

volumes:
  postgres-data:
    driver: ${DRIVER}
